spring.application.name=ev-charging-system

spring.datasource.url=jdbc:postgresql://aws-1-eu-central-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.nuwywbyhejurczuckgbt
spring.datasource.password=Ev.Vehicle2026

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.thymeleaf.cache=false

server.port=8081

charging.session.auto-end-delay-ms=60000
charging.session.auto-start-delay-ms=30000
charging.session.auto-start-battery-level=20
reservation.auto-expire-delay-ms=30000
reservation.auto-delete-delay-ms=3600000
reservation.auto-delete-retention-hours=24
